feat: added Maven java 21 pack
jenkins-x/jx3-pipeline-catalog pull request #1484
Opened 2024-02-16 16:21 UTC by freper138

2024-02-16 16:25 UTC, freper138 commented
/assign @msvticket

2024-02-16 16:29 UTC, msvticket commented
/ok-to-test

2024-02-19 13:09 UTC, msvticket requested changes
Almost ready

2024-02-19 13:09 UTC, msvticket commented on packs/maven-java21/charts/README.md
> +# Java 14 application
Update this

2024-02-19 15:18 UTC, freper138 commented on packs/maven-java21/charts/README.md
> +# Java 14 application
Updated to correct java version

2024-02-19 15:22 UTC, msvticket approved these changes

2024-02-19 15:23 UTC, merged