feat: allows to override ingress host
jenkins-x/jx3-pipeline-catalog pull request #1496
Opened 2024-05-09 15:05 UTC by yelhouti

2024-05-09 23:37 UTC, yelhouti commented
/assign @msvticket

2024-05-13 08:13 UTC, msvticket requested changes
Thank you for the PR!

Please address my comments! I only checked and added the comments to the "parent" chart, but they are are of course valid for all.

2024-05-13 08:13 UTC, msvticket commented on helm/charts/templates/ingress.yaml
> +{{- $host := (.Values.ingress.host | default (printf "%s%s%s" .Values.service.name .Values.jxRequirements.ingress.namespaceSubDomain .Values.jxRequirements.ingress.domain)) | quote }}
$host should be set within the if statement, as the other variables only needed if the ingress is actually created.

2024-05-13 08:13 UTC, msvticket commented on helm/charts/templates/ingress.yaml
> +{{- if or (.Values.ingress.host) (and (.Values.jxRequirements.ingress.domain) (not .Values.knativeDeploy)) }}
The ingress should never be created if knativeDeploy is true

2024-05-13 08:13 UTC, msvticket commented on helm/charts/templates/ingress.yaml
> +{{- end }}
This is an unrelated change that shouldn't be in this PR

2024-05-14 18:34 UTC, yelhouti commented
@msvticket is it possible to generate the child charts from the parent one, or do I need to change all charts manually ?

2024-05-15 07:17 UTC, msvticket commented
> is it possible to generate the child charts from the parent one, or do I need to change all charts manually ? 

In each "child" chart directory there is a Kptfile referring to the "parent" chart. So it seems like the intended work flow is to first merge the change to /helm/charts and then use `kpt pkg update` in each child chart to create a new PR.

> I modified all the charts manually could you please review

That works as well 😌

2024-05-15 07:22 UTC, msvticket commented
/ok-to-test

2024-05-15 07:23 UTC, msvticket approved these changes
Now it looks good. Thanks!

2024-05-15 07:25 UTC, merged